//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddTask
    {
        public AddTask() { }

        public AddTask(int id, string text)
        {
            itemID = id;
            this.text = text;
            isComplete = false;
        }
        
        public int Id { get; set; }
        public string text { get; set; }
        public Nullable<bool> isComplete { get; set; }
        public int itemID { get; set; }
    
        public virtual ToDoItem ToDoItem { get; set; }
    }
}
