//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Comment
    {
        public Comment() { }
        public Comment(string username, string text, int itemid)
        {
            this.itemid = itemid;
            this.text = text;
            this.username = username;
            this.time = DateTime.Now;
            this.itemid = itemid;
        }

        public int Id { get; set; }
        public string username { get; set; }
        public string text { get; set; }
        public System.DateTime time { get; set; }
        public int itemid { get; set; }
    }
}
