//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;

    public partial class ToDoItem
    {
        public ToDoItem()
        {
            this.AddTask = new HashSet<AddTask>();
        }

        public ToDoItem(string task, Nullable<System.DateTime> time, bool priority, int id)
        {
            Task = task;
            Mark = priority;
            FinishTime = time;
            userID = id;
            CreatingTime = DateTime.Now;

            this.AddTask = new HashSet<AddTask>();
        }

        public int Id { get; set; }
        public string Task { get; set; }
        public bool isComplete { get; set; }
        public bool Mark { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public Nullable<System.DateTime> RememberTime { get; set; }
        public string Note { get; set; }
        public string Comment { get; set; }
        public int userID { get; set; }
        public System.DateTime CreatingTime { get; set; }

        public virtual User User { get; set; }
        public virtual ICollection<AddTask> AddTask { get; set; }
    }
}
