//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data;
    using System.Data.SqlClient;

    public partial class User
    {
        public User()
        {
            this.ToDoItems = new HashSet<ToDoItem>();
        }

        public int Id { get; set; }

        [Required]
        [Display(Name = "User name")]
        public string login { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string password { get; set; }
        public Nullable<System.DateTime> regdata { get; set; }
        public string email { get; set; }

        [Display(Name = "Remember on this computer")]
        public bool remberMe { get; set; }

        public byte[] avatar { get; set; }

        public virtual ICollection<ToDoItem> ToDoItems { get; set; }

        public bool IsValid(string _username, string _password)
        {
            using (var cn = new SqlConnection(@"Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True"))
            {
                string _sql = @"SELECT [login] FROM [dbo].[Users] " +
                       @"WHERE [login] = @u AND [password] = @p";
                var cmd = new SqlCommand(_sql, cn);
                cmd.Parameters
                    .Add(new SqlParameter("@u", SqlDbType.NVarChar))
                    .Value = _username;
                cmd.Parameters
                    .Add(new SqlParameter("@p", SqlDbType.NVarChar))
                    .Value = Helpers.SHA1.Encode(_password);
                cn.Open();
                var reader = cmd.ExecuteReader();
                if (reader.HasRows)
                {
                    reader.Dispose();
                    cmd.Dispose();
                    return true;
                }
                else
                {
                    reader.Dispose();
                    cmd.Dispose();
                    return false;
                }
            }
        }
    }
}
